name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.3

      - name: Check code style
        run:
          ./vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: 12.2
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_version: 8.3
          php_extensions: "xdebug"
          args: --coverage-text
          coverage_clover: tests/result/clover.xml
        env:
          XDEBUG_MODE: coverage

#      - name: Coverage Check
#        uses: docker://ghcr.io/ericsizemore/phpunit-coverage-check-action
#        with:
#          clover_file: tests/result/clover.xml
#          threshold: 75